config/routes.rb
Rails.application.routes.draw do

  resources :teleporters, only: [:index, :search, :find, :search, :show] do
    get :find, :on => :collection
    get :search, :on => :collection
    resources :bookings, only: [:new]
  end

  resources :bookings, only: [:index, :show, :find, :create]

  root 'teleporters#find'

end

app/models/booking.rb
class Booking < ActiveRecord::Base

	validates :passenger_id, :teleporter_id, presence: true			  
	validates :passenger_id, uniqueness: {scope: :teleporter_id}	

	belongs_to :passenger
	belongs_to :teleporter

	def self.already_reserved_by_passenger?(email, teleporter_id)
		Booking.includes("passenger")
			   .where(teleporter_id: "#{teleporter_id}", 
			   		  passengers: { email: "#{email}" }).exists?
	end

end

app/models/departure.rb
class Departure < Place; end

app/models/destination.rb
class Destination < Place; end

app/models/passenger.rb
class EmailValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    unless value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
      record.errors[attribute] << (options[:message] || "is not an email")
    end
  end
end

class Passenger < ActiveRecord::Base

	validates :first_name, :last_name, presence: true
	validates :first_name, uniqueness: {scope: :last_name}
	validates :email, uniqueness:true, presence: true, email: true

	has_one :booking
	has_one :teleporter, through: :booking

end

app/models/place.rb
class Place < ActiveRecord::Base	
	validates :name, presence: true
	validates :name, uniqueness: {scope: :type}
	has_many :bookings
end

app/models/teleporter.rb
class Teleporter < ActiveRecord::Base
	
	validates :name, :departure_id, :destination_id, 
			  :departure_date, presence: true
	validates :name, uniqueness: {scope: :departure_date}
	validate  :departure_date_cannot_be_in_the_past

	validate  :refuse_same_departure_and_destination

	validate  :full

	belongs_to :departure, class_name: "Departure"
	belongs_to :destination, class_name: "Destination"

	has_many :bookings
	has_many :passengers, through: :bookings

	def refuse_same_departure_and_destination
	    if departure_id.present? && destination_id.present? && destination_id.eql?(departure_id)
	      errors.add(:destination_date, "Departure and Destination Points should not be the same")
	    end
	end

	def departure_date_cannot_be_in_the_past
		if departure_date.present? && departure_date < Time.now.utc
			errors.add(:departure_date, "can't be in the past")
		end
	end
	

	def busy?
		bookings.size >= 3
	end

	def available?
		bookings.size < 3
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  layout 'application'
  
  before_filter :initialize, only: [:index, :new]
  respond_to :html, :json

  def index
    @bookings = @bookings.paginate(:per_page => 20, :page => params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bookings }
    end
  end

  def new
    @teleporter = Teleporter.find(params[:teleporter_id])
    @booking = Booking.new(teleporter: @teleporter)
    @bookings = @bookings.paginate(:per_page => 20, :page => params[:page])
  end

  def create
    @teleporter = Teleporter.find(params[:teleporter_id])
    @passenger = Passenger.find_or_create_by(email: params[:email], 
                                             first_name: params[:first_name],
                                             last_name: params[:last_name])


    @booking = Booking.new(passenger:     @passenger,
                           teleporter_id: @teleporter.id) 

    respond_to do |format|
      if @booking.save
        format.html { redirect_to(:bookings, :notice => 'Registration successfull.') }
        format.json { render json: @booking, status: :created, location: @booking }
      else
        format.html { redirect_to(controller: :bookings, action: :new, teleporter_id: 3)}
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @booking = Booking.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @booking }
    end
  end

private
  def initialize
    @bookings = Booking.all.includes(:passenger, :teleporter)
  end

end

app/controllers/passengers_controller.rb
class PassengersController < ApplicationController
  def index
  end

  def search
  end
end

app/controllers/teleporters_controller.rb
class TeleportersController < ApplicationController
 
  helper_method :sort_column, :sort_direction
  respond_to :html, :json
  before_filter :search, :only => [:index, :create, :destroy]

  def index
    @teleporters = Teleporter.all.includes(:departure, :destination, :bookings)
    @teleporters = @teleporters.paginate(:per_page => 20, :page => params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @teleporters }
    end
  end

  def find
    @teleporter = Teleporter.new
  end

  def search
  	@teleporters = Teleporter.all.where(departure_id:   params[:book][:departure])
                                 .where(destination_id: params[:book][:destination])
                                 .where(departure_date: params[:start].to_date..params[:end].to_date)
                                 .order(:departure_date)
                                 .includes(:departure, :destination, :bookings)                                 
    @teleporters = @teleporters.paginate(:per_page => 20, :page => params[:page])
#
    respond_to do |format|
      format.html { render action: :index }
      format.json { render json: @teleporters }
    end
  end

  def create
    @teleporter = Teleporter.new(params[:teleporter])

    respond_to do |format|
      if @teleporter.save
        format.html { redirect_to(:teleporters, :notice => 'Registration successfull.') }
        format.json { render json: @teleporter, status: :created, location: @teleporter }
      else
        format.html { redirect_to("teleporter_sessions/new", :notice => ' error.')}
      end
    end
  end

  def show
    @teleporter = Teleporter.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @teleporter }
    end
  end

private
  def search_by_name
    @teleporters = Teleporters.order("#{sort_column} #{sort_direction}")
    @teleporters = @teleporters.where("name like ? ", "%#{params[:search]}%") unless params[:search].blank?
  end

  
  def sort_column
    Teleporters.column_names.include?(params[:sort]) ? params[:sort] : "id"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

	include WillPaginate::ViewHelpers
		
	def will_paginate_with_i18n(collection = nil, options = {})
		will_paginate collection, options.merge(:previous_label => I18n.t(:previous), :next_label => I18n.t(:next))
	end

	def sortable(column, title = nil)
    title ||= column.titleize
    css_class = (column.to_sym == sort_column.to_sym) ? "current #{sort_direction}" : nil
    direction = (column.to_sym == sort_column.to_sym && sort_direction == "asc") ? "desc" : "asc"
    result = flatten_keys(params).delete_if {|key| %w(sort direction).include?(key)}
    link_to title, result.merge({sort: column, direction: direction, search: params[:search], gare: params[:gare]}), {:class => css_class}
  end
  
  def direction_css(column)
    direction = (column.to_sym == sort_column.to_sym && sort_direction == "asc") ? "desc" : "asc"
    case direction
    when "asc"
     "icon-white icon-asc"
    when "desc"
      "icon-white icon-desc"
    end
  end #end of direction_css

  private
  def flatten_keys(options, pr = {}, prefix = nil)
    return "" unless options.kind_of? Hash
    options.collect do |key, value|
      full_key = prefix ? "#{prefix}[#{key}]" : key
      if value.is_a?(Hash)
        pr = flatten_keys(options[key], pr, full_key)
      else
        pr = pr.merge( full_key => options[key])
      end
    end
    pr
  end #end of encode_url(options)

end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/passengers_helper.rb
module PassengersHelper
end

app/helpers/teleporters_helper.rb
module TeleportersHelper
end

app/views/bookings/_bookings.erb
<%- model_class = Teleporter -%>

<table class="table table-striped table-sorting">
  <thead>
    <tr>
      <th scope="col">
        ID</button>
      </th>
      <th scope="col">
        Passenger</button>
      </th>
      <th scope="col">
        Teleporter</button>
      </th>
      <th scope="col">
        Created on</button>
      </th>
    </tr>
  </thead>
  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <% path = "/bookings/#{booking.id}" %>
        <td><%= link_to booking.id, booking_path(booking) %></td>
        <td><%= booking.passenger.first_name %></td>
        <td><%= booking.teleporter.departure.name %></td>
        <td><%= booking.teleporter.name %></td>
        <td><%=l booking.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="pagination-right" id="pagination">
  <%= render :partial => '/shared/pagination_booking', :resources => @bookings %>
</div>

app/views/bookings/_form.html.erb
<!-- Form booking -->
<%= form_for @booking, :url => {controller: :bookings, 
                                action: :create} do |f| %>

  <div class="modal-body">
    <% if @booking.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@booking.errors.count, "error") %> prohibited this booking from being saved:</h2>
        <ul>
        <% @booking.errors.booking.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= text_field_tag :first_name, nil, {required: true, placeholder: "First name"} %><br />
    </div>

    <div class="field">
      <%= text_field_tag :last_name, nil, {required: true, placeholder: "Last name"} %><br />
    </div>

    <div class="field">
      <%= email_field_tag :email, nil, {:autofocus => true, required: true, placeholder: "Email"} %>
    </div>

    <%= hidden_field_tag :teleporter_id, @teleporter.id,  {required: true} %>
  </div>
  <div class="modal-footer">
    <button type="submit" class="btn btn-primary"><i class="icon-plus"></i> Reserve</button>
  </div>

<% end %>

app/views/bookings/index.html.erb
<%- model_class = Booking -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>

<!-- Add, Filter and Search -->
<div class="row">
  <div class="span9">
    <!--<button type="select" class="btn" href="#add_popup" data-toggle="modal" ,
        class='btn btn-primary'><i class="icon-plus"></i> Add</button>-->
  </div>
  <div class="span3">
  </div>
  <%#= render "shared/search" %>
</div>

<div id="bookings"><%= render 'bookings' %></div>

app/views/bookings/new.html.erb
<h1>Book your Teleportation on <%= @teleporter.name %></h1>
<%- model_class = Booking -%>

<%= render 'form' %>

<%= link_to 'Teleporter List', bookings_path %>

app/views/bookings/show.html.erb
<h1>Booking#show</h1>
<p>Find me in app/views/booking/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Booking Application</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application"%>
    <%= javascript_include_tag "application" %>
    <%= stylesheet_link_tag "http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/redmond/jquery-ui.css", "application" %>
    <%= javascript_include_tag "application" %>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.10.4/themes/smoothness/jquery-ui.css">
    <script src="//code.jquery.com/jquery-1.10.2.js"></script>
    <script src="//code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
    <link rel="stylesheet" href="/resources/demos/style.css">

  </head>
  <body>
    <!-- Navbar -->
	  <header>
	    <div class="navbar navbar-fixed-top">
        <div class="navbar-inner">
          <div class="container"><!-- Collapsable nav bar -->
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </a>
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </a>
            <!-- Your site name for the upper left corner of the site -->
            <%= link_to "Booking", root_url, :class => "brand" %>
             <ul class="nav"></ul><ul class="nav"></ul>
             <ul class="nav">
                <li class="active"><%= link_to "Bookings", bookings_path %></li>
             </ul>

            <!-- Start of the nav bar content -->
            <div class="nav-collapse"><!-- Other nav bar content -->
              <ul class="nav pull-right">
                  <li>Sara Gomes</li>
                  <li class="divider-vertical"></li>
                  <li>Logout | Sign In | Sign Up</li>
              </ul>
            </div>
          </div>
        </div>
      </div>
	  </header>
	  <!-- FIN navbar -->
	  
   	<!-- Conteneur central -->
    <div class="container" id="global">
      <%= render :partial => "shared/flash", :locals => {:flash => flash} %><br /><br />
      <%= yield %>
    </div>
    <!-- FIN conteneur central -->
  </body>
</html>

app/views/passengers/index.html.erb
<h1>Passengers#index</h1>
<p>Find me in app/views/passengers/index.html.erb</p>

app/views/passengers/search.html.erb
<h1>Passengers#search</h1>
<p>Find me in app/views/passengers/search.html.erb</p>

app/views/shared/_flash.html.erb
<% if flash[:error] %>
<div class="alert alert-error">
  <button type="button" class="close" data-dismiss="alert">×</button>
  <h4>Erreur : </h4>
  <%= flash[:error] %>
</div>
<%elsif flash[:notice]%>
<div class="alert alert-info">
  <button type="button" class="close" data-dismiss="alert">×</button>
  <h4>Information : </h4>
  <%= flash[:notice] %>
</div>
<%elsif flash[:warning]%>
<div class="alert alert-block">
  <button type="button" class="close" data-dismiss="alert">×</button>
  <h4>Alerte : </h4>
  <%= flash[:warning] %>
</div>
<%elsif flash[:success]%>
<div class="alert alert-success">
  <button type="button" class="close" data-dismiss="alert">×</button>
  <h4>Succès :</h4>
  <%= flash[:success] %>
</div>
<%end %>

app/views/shared/_pagination.html.erb
 <div class = "pagination-right">
  <%= will_paginate @teleporters %>
 </div>

app/views/shared/_pagination_booking.html.erb
 <div class = "pagination-right">
  <%= will_paginate @bookings %>
 </div>

app/views/teleporters/_form.html.erb
<!-- Form teleporter -->
<%= form_tag("/teleporters/search", method: "get") do %>
  <div class="modal-body">
    <% if @teleporter.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@teleporter.errors.count, "error") %> prohibited this teleporter from being saved:</h2>
        <ul>
        <% @teleporter.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= collection_select :book, :departure, Departure.all, :id, :name, 
                            {:prompt => 'Departure point', :require => true}, 
                            {:class => 'multiselect'} %>
    </div>

    <div class="field">
      <%= collection_select :book, :destination, Destination.all, :id, :name, {:prompt => 'Destination point', :require => true}, {:class => 'multiselect'} %>
    </div>

      <%= text_field_tag :date, nil, {name: 'start', placeholder: "Start date", id: 'start', class: 'input-small', 'data-behaviour' =>'datepicker'} %> 
      <span class='add-on'>to</span>
      <%= text_field_tag :date, nil, {name: 'end', placeholder: "End date", id: 'end', class: 'input-small', 'data-behaviour' =>'datepicker'} %> 
    
  </div>
  <div class="modal-footer">
    <button type="submit" class="btn btn-primary"><i class="icon-plus"></i> Find</button>
  </div>
<% end %>

app/views/teleporters/_teleporters.erb
<%- model_class = Teleporter -%>

<table class="table table-striped table-sorting">
  <thead>
    <tr>
      <th scope="col">
        ID</button>
      </th>
      <th scope="col">
        Name</button>
      </th>
      <th scope="col">
        Departure Point</button>
      </th>
      <th scope="col">
        Destination Point</button>
      </th>
      <th scope="col">
        Date</button>
      </th>
      <th scope="col">
        Created on</button>
      </th>
      <th scope="col"><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @teleporters.each do |teleporter| %>
      <tr>
        <% path = "/teleporters/#{teleporter.id}" %>
        <td><%= link_to teleporter.id, teleporter_path(teleporter) %></td>
        <td><%= teleporter.name %></td>
        <td>
            <% teleporter.bookings.each do |booking| %>
              <%= booking.passenger.first_name %> <%= booking.passenger.last_name %></br>
            <% end %>
        </td>
        <td><%= teleporter.departure.name %></td>
        <td><%= teleporter.destination.name %></td>
        <td><%=l teleporter.departure_date %></td>
        <td>
          <% if teleporter.busy? %>
            <a href="<%= teleporter_path(teleporter) %>" class='btn btn-mini btn-danger'>
              <i class="icon-remove-sign"> </i>Busy
            </a>
          <% else %>
            <a href="/teleporters/<%= teleporter.id %>/bookings/new" class='btn btn-mini'>
              <i class="icon-remove-sign"> </i>Available
            </a>
            <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="pagination-right" id="pagination">
  <%= render :partial => '/shared/pagination' %>
</div>

app/views/teleporters/create.html.erb
<h1>Booking#create</h1>
<p>Find me in app/views/booking/create.html.erb</p>

app/views/teleporters/find.html.erb
<h1>Find your Teleportation</h1>

<%= render 'form' %>

<%= link_to 'Teleporter List', "teleporters_path" %>

app/views/teleporters/index.html.erb
<%- model_class = Teleporter -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>

<!-- Add, Filter and Search -->
<div class="row">
  <div class="span9">
    <!--<button type="select" class="btn" href="#add_popup" data-toggle="modal" ,
        class='btn btn-primary'><i class="icon-plus"></i> Add</button>-->
  </div>
  <div class="span3">
  </div>
  <%#= render "shared/search" %>
</div>

<div id="teleporters"><%= render 'teleporters' %></div>

app/views/teleporters/index.js.erb
$('#tasks').html('<%= escape_javascript(render("tasks")) %>');
$('#pagination').html('<%= escape_javascript(render("/shared/pagination")) %>');
$('#today_tasks').html("<%= escape_javascript(pluralize(@current_user.today_tasks.count, 'task') )%>");
<%= raw @categories %>

app/views/teleporters/new.html.erb
<h1>Reserve your Teleportation</h1>

<%= render 'form' %>

<%= link_to 'Teleporter List', bookings_path %>

app/views/teleporters/show.html.erb
<%- model_class = Teleporter -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong>Identifiant:</strong></dt>
  <dd><%= @teleporter.id %>&nbsp</dd>
  <dt><strong>Nom:</strong></dt>
  <dd><%= @teleporter.name %>&nbsp</dd>
  <dt><strong>Departure Point:</strong></dt>
  <dd><%= @teleporter.departure.name %>&nbsp</dd>
  <dt><strong>Destination Point:</strong></dt>
  <dd><%= @teleporter.destination.name %>&nbsp</dd>
  <dt><strong>Departure:date</strong></dt>
  <dd><%=l @teleporter.departure_date %>&nbsp</dd>
  <dt><strong>Nr. de connexions:</strong></dt>
  <dt><strong>Crée le:</strong></dt>
  <dd><%=l @teleporter.created_at %>&nbsp</dd>
</dl>

<h3>Teleporter passangers</h3>

<% if @teleporter.passengers.empty? %>
  No passenger. This teleporter is completely available!.
<% else %>
  <table class="table table-striped table-sorting">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">First name</th>
        <th scope="col">Last name</th>
        <th scope="col">email</th>
        <th scope="col">Created at</th>
      </tr>
    </thead>
    <tbody>
      <% @teleporter.passengers.each do |passenger| %>
        <tr>
          <td><%= passenger.id %></td>
          <td><%= passenger.first_name %></td>
          <td><%= passenger.last_name %></td>
          <td><%= passenger.email %></td>
          <td><%=l passenger.created_at %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              teleporters_path, {method: :get, :class => 'btn'}  %>
  <%#= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_backoffice_teleporter_path(@teleporter), :class => 'btn' %>
  <%#= link_to t('.destroy', :default => t("helpers.links.destroy")),
              teleporter_path(@teleporter),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>